(cl:in-package pan_tilt_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          SERIAL_NUM-VAL
          SERIAL_NUM
          HW_VERSION-VAL
          HW_VERSION
          BD_VERSION-VAL
          BD_VERSION
          SW_VERSION-VAL
          SW_VERSION
          SET_ZERO-VAL
          SET_ZERO
          SPEED-VAL
          SPEED
          YAW_GOAL-VAL
          YAW_GOAL
          PITCH_GOAL-VAL
          PITCH_GOAL
          RESERVED-VAL
          RESERVED
          DRIVER_EC-VAL
          DRIVER_EC
          ENCODER_EC-VAL
          ENCODER_EC
          YAW_NOW-VAL
          YAW_NOW
          PITCH_NOW-VAL
          PITCH_NOW
          YAW_TEMP-VAL
          YAW_TEMP
          PITCH_TEMP-VAL
          PITCH_TEMP
          YAW_RAW-VAL
          YAW_RAW
          PITCH_RAW-VAL
          PITCH_RAW
          LOOP_EC-VAL
          LOOP_EC
          LOOP_TIME-VAL
          LOOP_TIME
))